/** Seed quizzes excluded from the public catalog due to copyright/trademark risk. */
export const BLOCKED_SEED_QUIZ_IDS = new Set([
  "pop-hits-2010s",
  "kpop-hits-global",
  "disney-classics-ost",
  "british-rock-legends",
  "latin-pop-global",
  "90s-hits-anthems",
  "tiktok-viral-hits",
  "christmas-songs-global",
  "edm-party-hits",
  "taylor-swift-era",
  "movie-posters-icons",
  "netflix-hit-shows",
  "marvel-heroes",
  "harry-potter-magic",
  "star-wars-galaxy",
  "pixar-magic",
  "hollywood-legends",
  "pokemon-gen1",
  "anime-crop-hard",
  "gaming-icons",
  "meme-internet-culture",
  "fast-food-logos",
  "tech-logos-crop",
  "luxury-car-brands",
  "football-clubs-world",
  "nba-teams",
  "sports-logos-crop",
  "sneaker-brands-crop",
  "variety-mixed-mega",
  "landmarks-crop",
  "seven-wonders-world",
  "world-capitals-landmarks",
  // Replaced by higher-quality Machugi-style packs
  "world-flags-easy",
  "europe-flags-challenge",
  "asia-flags-mastery",
  "africa-flags-explorer",
  "south-america-flags",
  "usa-state-flags",
  "world-mountains",
  "world-rivers",
  "solar-system",
  "world-birds",
  "unesco-landmarks",
  "japanese-culture",
  "world-deserts",
  "safari-wildlife",
  "flags-tricky-hard",
  "korean-street-food",
  "world-food-icons",
  // Low-quality crops / duplicates replaced by Machugi-style packs
  "animal-closeup-crop",
  "birds-youve-seen",
  "capitals-world-mix",
  "landmarks-round-two",
]);

export function isBlockedSeedQuiz(id: string): boolean {
  return BLOCKED_SEED_QUIZ_IDS.has(id);
}
